/*
 * File: app/mda/view/gmo/gma/resolutor/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('gma.view.gmo.gma.resolutor.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gma.resolutor.winMtto'
    ],
    requires: [
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.toolbar.Paging',
        'Ext.form.field.Number',
        'Ext.grid.plugin.CellEditing',
        'Ext.form.field.Hidden'
    ],

    height: 540,
    itemId: 'wingmaResolutor',
    width: 1246,
    layout: 'fit',
    title: 'Mantenimiento de Resolutores',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Menu de opciones'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            iconCls: 'btnSave',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCerrar',
                            iconCls: 'btnClose',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    itemId: 'frmgmaresolutor',
                    layout: 'fit',
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/process/lst_gma_resolutor.php',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            itemId: 'srv_codigo',
                                            fieldLabel: 'Area | Servicio:',
                                            labelAlign: 'top',
                                            name: 'srv_codigo',
                                            displayField: 'srv_denominacion',
                                            queryMode: 'local',
                                            store: 'gmo.gmo.servicio.stservicio',
                                            valueField: 'srv_codigo'
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'pai_codigo',
                                            margin: '0 0 0 3',
                                            fieldLabel: 'Region',
                                            labelAlign: 'top',
                                            name: 'pai_codigo',
                                            readOnly: true,
                                            displayField: 'pai_denominacion',
                                            store: 'gmo.global.glbpais.stglbpais',
                                            valueField: 'pai_codigo'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtcriterio',
                                            width: 279,
                                            fieldLabel: 'Criterio:',
                                            labelWidth: 50,
                                            emptyText: 'Ingresar Nombre de usuario.'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnRecuperar',
                                            iconCls: 'btnRetrieve',
                                            text: 'Recuperar'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnAdicionar',
                                            iconCls: 'btnAdicionar',
                                            text: 'Adicionar'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnEliminar',
                                            iconCls: 'btnEliminar',
                                            text: 'Eliminar'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            flex: 1,
                                            width: 606,
                                            layout: 'fit',
                                            title: 'Usuarios Activos',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    itemId: 'grdglprofile',
                                                    store: 'gmo.global.glprofile.stglprofile',
                                                    viewConfig: {
                                                        itemId: 'grvglprofile'
                                                    },
                                                    columns: [
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'per_codigo',
                                                            text: 'Per Codigo',
                                                            format: '00'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            hidden: true,
                                                            dataIndex: 'per_tipo',
                                                            text: 'Per Tipo'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 234,
                                                            dataIndex: 'per_nombrecompleto',
                                                            text: 'Apellidos y Nombres'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 126,
                                                            dataIndex: 'per_nrodocidentidad',
                                                            text: 'Cuenta'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'pai_codigo',
                                                            text: 'Pai Codigo',
                                                            format: '00'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'pai_denominacion',
                                                            text: 'Region'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 228,
                                                            dataIndex: 'ema_denominacion',
                                                            text: 'Email'
                                                        }
                                                    ],
                                                    dockedItems: [
                                                        {
                                                            xtype: 'pagingtoolbar',
                                                            dock: 'bottom',
                                                            width: 360,
                                                            displayInfo: true,
                                                            store: 'gmo.global.glprofile.stglprofile'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            flex: 1,
                                            layout: 'fit',
                                            title: 'Usuarios Registrados',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    itemId: 'grdgmaresolutor',
                                                    width: 365,
                                                    store: 'gmo.gma.resolutor.stresolutorpaisrv',
                                                    columns: [
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'rse_codigo',
                                                            text: 'Rse Codigo',
                                                            format: '00'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'pai_codigo',
                                                            text: 'Pai Codigo',
                                                            format: '00'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            hidden: true,
                                                            dataIndex: 'pai_denominacion',
                                                            text: 'Pai Denominacion'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'srv_codigo',
                                                            text: 'Srv Codigo',
                                                            format: '00'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            hidden: true,
                                                            dataIndex: 'srv_denominacion',
                                                            text: 'Srv Denominacion'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'per_codigo',
                                                            text: 'Per Codigo',
                                                            format: '00'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 364,
                                                            dataIndex: 'per_nombrecompleto',
                                                            text: 'Nombre'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 144,
                                                            dataIndex: 'per_nrodocidentidad',
                                                            text: 'Codigo'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            hidden: true,
                                                            dataIndex: 'ema_denominacion',
                                                            text: 'Ema Denominacion'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            width: 85,
                                                            align: 'center',
                                                            dataIndex: 'rse_nivel',
                                                            text: 'Nivel Usuario',
                                                            format: '00',
                                                            editor: {
                                                                xtype: 'numberfield',
                                                                submitValue: false,
                                                                maxValue: 3,
                                                                minValue: 1
                                                            }
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            hidden: true,
                                                            dataIndex: 'rse_niveldescripcion',
                                                            text: 'Rse Niveldescripcion'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            hidden: true,
                                                            dataIndex: 'rse_estado',
                                                            text: 'rse_Estado'
                                                        }
                                                    ],
                                                    plugins: [
                                                        Ext.create('Ext.grid.plugin.CellEditing', {
                                                            pluginId: 'editor',
                                                            clicksToEdit: 1
                                                        })
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'accion',
                            fieldLabel: 'Label',
                            name: 'accion'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});