/*
 * File: app/mda/model/gmo/global/glprofile/mdglprofile.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('gma.model.gmo.global.glprofile.mdglprofile', {
    extend: 'Ext.data.Model',

    alternateClassName: [
        'gmo.global.glprofile.mdglprofile'
    ],
    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'per_codigo',

    fields: [
        {
            name: 'per_codigo',
            type: 'int'
        },
        {
            name: 'per_tipo',
            type: 'string'
        },
        {
            name: 'per_nombrecompleto',
            type: 'string'
        },
        {
            name: 'per_nrodocidentidad',
            type: 'string'
        },
        {
            name: 'pai_codigo',
            type: 'int'
        },
        {
            name: 'pai_denominacion',
            type: 'string'
        },
        {
            name: 'ema_denominacion',
            type: 'string'
        }
    ]
});