/*
 * File: app/mda/controller/gmo/gma/resolutor/ctrMain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('gma.controller.gmo.gma.resolutor.ctrMain', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gma.resolutor.ctrMain'
    ],

    refs: [
        {
            ref: 'Main',
            selector: '#vpngmaResolutor'
        }
    ],

    onBtnRecuperarClick: function(button, e, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    ln_pai_codigo = vpn.down('#cmb_pais').getValue(),

                    ls_criterio = vpn.down('#txtcriterio').getValue(),

                    st_resolutor  = vpn.down('#grdgmaResolutor').getStore();

                    st_resolutor.load({
                        params:{
                            'operacion':2,
                            'rse_codigo':0,
                            'pai_codigo':ln_pai_codigo,
                            'criterio':ls_criterio
                        }
                    });
    },

    onBtnNuevoClick: function(button, e, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    ln_pai_codigo = vpn.down('#cmb_pais').getValue(),

                    win = Ext.create('gma.view.gmo.gma.resolutor.winMtto');

                    win.down('#accion').setValue(1);

                    win.down('#pai_codigo').setValue(parseInt(ln_pai_codigo));

                    win.show();
    },

    onBtnAnularClick: function(button, e, eOpts) {
               var me= this,

                    vp=me.getMain(),

                    grid=vp.down('#grdgmaResolutor'),

                    rse_codigo=[],

                    sm=grid.getSelectionModel();

                if (sm.hasSelection()===false){

                    Ext.MessageBox.alert('Debe seleccionar registro a anular');

                    return;
                }

                var rec=sm.getSelection()[0];

                var ls_url='/library/process/lst_gma_resolutor.php';

                rse_codigo.push(rec.data.rse_codigo);

                var ls_params={
                    'operacion' 	: 1,
                    'accion'		: 3,
                    'rse_codigo[]'	: rse_codigo
                };

                Ext.MessageBox.confirm('Mensaje','Desea anular registro seleccionado',function(rsp){

                    if(rsp==='yes'){

                         me.getController('gmo.global.utiles.ctrfuncion').fn_AjaxRequest(ls_params,ls_url,function(val){

                           if(val){

                               grid.getStore().remove(rec);

                               Ext.Msg.alert('Mensaje','Anulacion de registro realizado correctamente');
                           }

                         });
                    }

                });


    },

    onBtnCerrarClick: function(button, e, eOpts) {

    },

    onVpngmaResolutorAfterRender: function(component, eOpts) {
        var me = this,

            vpn = me.getMain(),

            cmb_pais = vpn.down('#cmb_pais'),

            st_pais = vpn.down('#cmb_pais').getStore();

        st_pais.load({
            params:{
                'operacion':2
            },
            callback:function(records,options,success){
               if(success&&records[0]!==undefined){

                   cmb_pais.setValue(records[0].data.pai_codigo);
               }
            }

        });
    },

    onCmb_paisChange: function(field, newValue, oldValue, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    btn_recuperar = vpn.down('#btnRecuperar');

                    if (newValue===oldValue){ return;}

                    me.onBtnRecuperarClick(me,me.btn_recuperar);

    },

    onTxtcriterioSpecialkey: function(field, e, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    btn_recuperar = vpn.down('#btnRecuperar');

                    if(e.getKey()==e.ENTER){

                        me.onBtnRecuperarClick(me,me.btn_recuperar);
                    }
    },

    onBtnRecuperardetalleClick: function(button, e, eOpts) {
                    var me = this,

                        vpn = me.getMain(),

                        grd = vpn.down('#grdgmaResolutor'),

                        sm = grd.getSelectionModel(),

                        ls_criterio = vpn.down('#txcriteriodet'),

                        st_responsable = vpn.down('#grdgmaresponsable').getStore();

                        if (sm.hasSelection()===false){

                            return;
                        }

                        var rec= sm.getSelection()[0];

                        st_responsable.load({
                            params:{
                                'operacion':2,
                                'rse_codigo':rec.data.rse_codigo,
                                'criterio':ls_criterio
                            }
                        });
    },

    onBtnAdicionardetalleClick: function(button, e, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    grd = vpn.down('#grdgmaResolutor'),

                    sm = grd.getSelectionModel();

                    if (sm.hasSelection()===false){

                        Ext.MessageBox.show({
                            title  : 'Mensaje' ,
                            msg    : 'Debe seleccionar un resolutor a quien desea agregar responsabilidades',
                            buttons: Ext.MessageBox.OK,
                            icon   : Ext.MessageBox.WARNING
                        });

                        return;
                    }

                    var rec = sm.getSelection()[0],

                    win = Ext.create('gma.view.gmo.gma.responsable.winMtto');

                        win.down('#rse_codigo').setValue(rec.data.rse_codigo);

                        win.down('#srv_denominacion').setValue(rec.data.srv_denominacion);

                        win.down('#per_nombrecompleto').setValue(rec.data.per_nombrecompleto);

                        win.down('#rse_niveldescripcion').setValue(rec.data.rse_niveldescripcion);

                        win.down('#pai_denominacion').setValue(rec.data.pai_denominacion);

                        win.down('#accion').setValue(1);

                        win.show();

    },

    onBtnAnulardetalleClick: function(button, e, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    grd = vpn.down('#grdgmaresponsable'),

                    sm = grd.getSelectionModel(),

                    rpe_codigo=[];

                    if (sm.hasSelection()===false){

                        Ext.MessageBox.alert('Mensaje','Debe seleccionar registro a anular');

                        return;
                    }

                var rec=sm.getSelection()[0];

                var ls_url='/library/process/lst_gma_responsable.php';

                rpe_codigo.push(rec.data.rpe_codigo);

                var ls_params={
                    'operacion' 	: 1,
                    'accion'		: 3,
                    'rpe_codigo[]'	: rpe_codigo
                };

                Ext.MessageBox.confirm('Mensaje','Desea anular registro seleccionado',function(rsp){

                    if(rsp==='yes'){

                         me.getController('gmo.global.utiles.ctrfuncion').fn_AjaxRequest(ls_params,ls_url,function(val){

                           if(val){

                               grd.getStore().remove(rec);

                               Ext.Msg.alert('Mensaje','Anulacion de registro realizado correctamente');
                           }

                         });
                    }

                });




    },

    onTxtcriteriodetSpecialkey: function(field, e, eOpts) {

    },

    onGrdgmaResolutorSelectionChange: function(model, selected, eOpts) {
                var me  = this,

                    vpn = me.getMain(),

                    btn_recuperar = vpn.down('#btnRecuperardetalle');

                    me.onBtnRecuperardetalleClick(me,me.btn_recuperar);
    },

    init: function(application) {
        this.control({
            "#vpngmaResolutor #btnRecuperar": {
                click: this.onBtnRecuperarClick
            },
            "#vpngmaResolutor #btnNuevo": {
                click: this.onBtnNuevoClick
            },
            "#vpngmaResolutor #btnAnular": {
                click: this.onBtnAnularClick
            },
            "#vpngmaResolutor #btnCerrar": {
                click: this.onBtnCerrarClick
            },
            "#vpngmaResolutor": {
                afterrender: this.onVpngmaResolutorAfterRender
            },
            "#vpngmaResolutor #cmb_pais": {
                change: this.onCmb_paisChange
            },
            "#vpngmaResolutor #txtcriterio": {
                specialkey: this.onTxtcriterioSpecialkey
            },
            "#vpngmaResolutor #btnRecuperardetalle": {
                click: this.onBtnRecuperardetalleClick
            },
            "#vpngmaResolutor #btnAdicionardetalle": {
                click: this.onBtnAdicionardetalleClick
            },
            "#vpngmaResolutor #btnAnulardetalle": {
                click: this.onBtnAnulardetalleClick
            },
            "#vpngmaResolutor #txtcriteriodet": {
                specialkey: this.onTxtcriteriodetSpecialkey
            },
            "#grdgmaResolutor": {
                selectionchange: this.onGrdgmaResolutorSelectionChange
            }
        });
    }

});
