/*
 * File: app/mda/controller/gmo/gma/servicio/ctrMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.controller.gmo.gma.servicio.ctrMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gma.servicio.ctrMtto'
    ],

    refs: [
        {
            ref: 'Main',
            selector: '#vpmaingmaServicio'
        },
        {
            ref: 'Mtto',
            selector: '#wingmaServicio'
        }
    ],

    onBtnCerrarClick: function(button, e, eOpts) {
                button.up('window').close();
    },

    onBtnGuardarClick: function(button, e, eOpts) {
                var me = this,

                    win = me.getMtto(),

                    vpn = me.getMain(),

                    ln_accion = win.down('#accion'),

                    frm = win.down('#frmServicio');

                    if (frm.isValid()===false){

                        Ext.Message.alert('Mensaje','Datos de formulario incompleto');

                        return;
                    }

                    frm.submit({

                        success: function(form, action){

                        var objJson =Ext.JSON.decode(action.response.responseText);

                            if (objJson.success){
                                Ext.MessageBox.alert('Mensaje',objJson.msg);
                                vpn.down('#grdServicio').getStore().reload();
                                vpn.down('#grdServicio').getSelectionModel().deselectAll();
                                win.close();
                            }
                    },
                    failure: function(form,action){

                        var objJson =Ext.JSON.decode(action.response.responseText);

                        Ext.MessageBox.alert('Mensaje',objJson.msgError);

                    },
                params:{
                    operacion:1,
                    accion:ln_accion.getValue()
            }

        });

    },

    init: function(application) {
        this.control({
            "#wingmaServicio #btnCerrar": {
                click: this.onBtnCerrarClick
            },
            "#wingmaServicio #btnGuardar": {
                click: this.onBtnGuardarClick
            }
        });
    }

});
