/*
 * File: app/mda/controller/gmo/gma/responsable/ctrMain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.controller.gmo.gma.responsable.ctrMain', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gma.responsable.ctrMain'
    ],

    refs: [
        {
            ref: 'Main',
            selector: '#vpngmaresponsable'
        }
    ],

    onBtnRecuperarClick: function(button, e, eOpts) {
        var me = this,

            vpn = me.getMtto(),

            ls_criterio = vpn.down('#txtcriterio').getValue(),

            ln_srv_codigo = vpn.down('#srv_codigo').getValue(),

            st_rsp = vpn.down('#grdResponsable').getStore();

        st_rsp.load({
            params:{
                'accion':2,
                'srv_codigo':ln_srv_codigo,
                'txtcriterio':ls_criterio
            }
        });

    },

    onBtnNuevoClick: function(button, e, eOpts) {
        var me =this,

            vpn = me.getMain(),

            win = Ext.create('mda.view.gmo.gma.responsable.winMtto');

            win.down('#accion').setValue(1);

            win.show();

    },

    onBtnAnularClick: function(button, e, eOpts) {

    },

    onBtnCerrarClick: function(button, e, eOpts) {
                 var me = this,

                     vpn = me.getMain();

                     vpn.close();

    },

    onVpngmaresponsableAfterRender: function(component, eOpts) {
                var me = this,

                    vpn = me.getMain(),

                    st_srv = vpn.down('#srv_codigo').getStore();

                    st_srv.load({
                        params:{
                            'operacion':2,
                            'srv_codigo':0
                        }
                    });
    },

    init: function(application) {
        this.control({
            "#vpngmaresponsable #btnRecuperar": {
                click: this.onBtnRecuperarClick
            },
            "#vpngmaresponsable #btnNuevo": {
                click: this.onBtnNuevoClick
            },
            "#vpngmaresponsable #btnAnular": {
                click: this.onBtnAnularClick
            },
            "#vpngmaresponsable #btnCerrar": {
                click: this.onBtnCerrarClick
            },
            "#vpngmaresponsable": {
                afterrender: this.onVpngmaresponsableAfterRender
            }
        });
    }

});
