/*
 * File: app/mda/controller/gmo/gma/responsable/ctrMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.controller.gmo.gma.responsable.ctrMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gma.responsable.ctrMtto'
    ],

    refs: [
        {
            ref: 'Mtto',
            selector: '#winMttoResponsable'
        }
    ],

    onWinMttoResponsableAfterRender: function(component, eOpts) {
                var me = this,

                    win = me.getMtto(),

                    st_pais = win.down('#pai_codigo').getStore(),

                    st_srv  = win.down('#srv_codigo').getStore();

                    st_pais.load({
                        params:{
                            'operacion':2
                        }
                    });

                    st_srv.load({
                        params:{
                            'operacion':2,
                            'srv_codigo':0
                        }
                    });
    },

    init: function(application) {
        this.control({
            "#winMttoResponsable": {
                afterrender: this.onWinMttoResponsableAfterRender
            }
        });
    }

});
