/*
 * File: app/mda/view/gmo/gma/requerimiento/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.view.gmo.gma.requerimiento.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gma.requerimiento.winMtto'
    ],
    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.field.Hidden',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number'
    ],

    height: 213,
    itemId: 'wingmaRequerimiento',
    width: 638,
    layout: 'fit',
    title: 'Mantenimiento de Requerimientos x Servicio',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'frmRequerimiento',
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/process/lst_gma_requerimiento.php',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Menu de opciones:'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnNuevo',
                                    iconCls: 'btnNew',
                                    text: 'Nuevo'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnGuardar',
                                    iconCls: 'btnSave',
                                    text: 'Guardar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCerrar',
                                    iconCls: 'btnClose',
                                    text: 'Cerrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'accion',
                            fieldLabel: 'Label',
                            name: 'accion'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'rqe_codigo',
                            fieldLabel: 'Label',
                            name: 'rqe_codigo',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'srv_codigo',
                            fieldLabel: 'Label',
                            name: 'srv_codigo'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'srv_denominacion',
                            fieldLabel: 'Servicio',
                            labelAlign: 'top',
                            name: 'srv_denominacion',
                            fieldStyle: 'font-size:11px; text-transform: uppercase;',
                            readOnly: true,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'rqe_denominacion',
                            fieldLabel: 'Requerimiento:',
                            labelAlign: 'top',
                            name: 'rqe_denominacion',
                            fieldStyle: 'font-size:11px; text-transform: uppercase;',
                            allowBlank: false,
                            emptyText: 'Especificar denominacion de requerimiento'
                        },
                        {
                            xtype: 'fieldcontainer',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    itemId: 'rqe_prioridad',
                                    fieldLabel: 'Prioridad',
                                    labelAlign: 'top',
                                    name: 'rqe_prioridad',
                                    fieldStyle: 'font-size:11px; text-transform: uppercase;',
                                    allowBlank: false,
                                    emptyText: 'Seleccionar nivel de prioridad de requerimiento ',
                                    displayField: 'descripcion',
                                    queryMode: 'local',
                                    store: 'gmo.gma.atributo.stprioridad',
                                    valueField: 'codigo'
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'rqe_tiemporpta',
                                    margin: '0 0 0 10',
                                    fieldLabel: 'Tiempo Rpta (Hrs.)',
                                    labelAlign: 'top',
                                    name: 'rqe_tiemporpta',
                                    fieldStyle: 'font-size:11px; text-transform: uppercase;',
                                    emptyText: '',
                                    minValue: 0
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});