/*
 * File: app/mda/controller/gmo/gma/requerimiento/ctrMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.controller.gmo.gma.requerimiento.ctrMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gma.requerimiento.ctrMtto'
    ],

    refs: [
        {
            ref: 'Main',
            selector: '#vpmaingmaServicio'
        },
        {
            ref: 'Mtto',
            selector: '#wingmaRequerimiento'
        }
    ],

    onWingmaRequerimientoAfterRender: function(component, eOpts) {
                var me  =this,

                    win = me.getMtto(),

                    st_prioridad = win.down('#rqe_prioridad').getStore();

                    st_prioridad.load({
                        params:{
                            'operacion':2
                        }
                    });
    },

    onBtnNuevoClick: function(button, e, eOpts) {
                var me =this,

                    win = me.getMtto();

                    win.down('#rqe_codigo').setValue(0);

                    win.down('#rqe_denominacion').setValue('');

                    win.down('#accion').setValue(1);


    },

    onBtnGuardarClick: function(button, e, eOpts) {
                var me = this,

                    win = me.getMtto(),

                    vpn = me.getMain(),

                    frm = win.down('#frmRequerimiento'),

                    ln_accion = win.down('#accion');

                    if (frm.isValid()===false){

                        Ext.MessageBox.alert('Mensaje','Datos de formulario incompleto');

                        return;
                    }

                   frm.submit({

                        success: function(form, action){

                        var objJson =Ext.JSON.decode(action.response.responseText);

                            if (objJson.success){
                                Ext.MessageBox.alert('Mensaje',objJson.msg);
                                vpn.down('#grdRequerimiento').getStore().reload();
                                vpn.down('#grdRequerimiento').getSelectionModel().deselectAll();

                                if (ln_accion.getValue()==='2'){win.close();}

                            }
                        },
                        failure: function(form,action){

                            var objJson =Ext.JSON.decode(action.response.responseText);

                            Ext.MessageBox.alert('Mensaje',objJson.msgError);

                        },
                        params:{
                            operacion:1,
                            accion:ln_accion.getValue()
                        }
                   });

    },

    onBtnCerrarClick: function(button, e, eOpts) {
                button.up('window').close();
    },

    init: function(application) {
        this.control({
            "#wingmaRequerimiento": {
                afterrender: this.onWingmaRequerimientoAfterRender
            },
            "#btnNuevo": {
                click: this.onBtnNuevoClick
            },
            "#btnGuardar": {
                click: this.onBtnGuardarClick
            },
            "#btnCerrar": {
                click: this.onBtnCerrarClick
            }
        });
    }

});
