/*
 * File: app/mda/view/gmo/gma/responsable/vpmain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.view.gmo.gma.responsable.vpmain', {
    extend: 'Ext.panel.Panel',

    alternateClassName: [
        'gmo.gma.responsable.vpmain'
    ],
    requires: [
        'Ext.grid.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Number'
    ],

    height: 600,
    itemId: 'vpngmaresponsable',
    width: 1200,
    layout: 'fit',
    title: 'Mantenimiento de Responsables x Tema y Región',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'grdResponsable',
                    store: 'gmo.gma.responsable.stresponsable',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'pai_codigo',
                                    fieldLabel: 'Region:',
                                    labelWidth: 50,
                                    name: 'pai_codigo',
                                    displayField: 'pai_denominacion',
                                    queryMode: 'local',
                                    store: 'gmo.global.glbpais.stglbpais',
                                    valueField: 'pai_codigo'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtcriterio',
                                    margin: '0 0 0 10',
                                    width: 268,
                                    fieldLabel: 'Criterio',
                                    labelWidth: 50,
                                    name: 'txtcriterio',
                                    emptyText: 'Criterio de Busqueda'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Menu de opciones:'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRecuperar',
                                    iconCls: 'btnRetrieve',
                                    text: 'Recuperar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnNuevo',
                                    iconCls: 'btnNew',
                                    text: 'Nuevo'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnModificar',
                                    iconCls: 'btnEdit',
                                    text: 'Modificar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnAnular',
                                    iconCls: 'btnDelete',
                                    text: 'Anular'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCerrar',
                                    iconCls: 'btnClose',
                                    text: 'Cerrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'gmo.gma.responsable.stresponsable'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            text: 'Datos de Responsable',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 309,
                                    dataIndex: 'per_nombrecompleto',
                                    text: 'Apellidos y Nombres'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 112,
                                    dataIndex: 'per_nrodocidentidad',
                                    text: 'Nro. Documento'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 220,
                                    dataIndex: 'ema_denominacion',
                                    text: 'Email'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            text: 'Responsabilidad',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 296,
                                    dataIndex: 'srv_denominacion',
                                    text: 'Servicio'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 272,
                                    dataIndex: 'rpe_denominacion',
                                    text: 'Tema'
                                }
                            ]
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'rpe_codigo',
                            text: 'Rpe Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'pai_codigo',
                            text: 'Pai Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'pai_denominacion',
                            text: 'Pai Denominacion'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'srv_codigo',
                            text: 'Srv Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'rqe_codigo',
                            text: 'Rqe Codigo'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'per_codigo',
                            text: 'Per Codigo',
                            format: '00'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});