/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'gmo.gma.servicio.mdservicio',
        'gmo.gma.requerimiento.mdrequerimiento',
        'gmo.gma.atributo.mdprioridad'
    ],
    stores: [
        'gmo.gma.servicio.stservicio',
        'gmo.gma.requerimiento.strequerimiento',
        'gmo.gma.atributo.stprioridad'
    ],
    views: [
        'gmo.gma.servicio.vpmain',
        'gmo.gma.servicio.winMtto',
        'gmo.gma.requerimiento.winMtto'
    ],
    appFolder: 'app/mda',
    appProperty: 'mda',
    controllers: [
        'gmo.gma.servicio.ctrMain',
        'gmo.gma.servicio.ctrMtto',
        'MyController',
        'gmo.gma.requerimiento.ctrMtto',
        'gmo.global.utiles.ctrfuncion'
    ],
    name: 'mda',
    title: 'Gestion de Tickets ',

    launch: function() {
        Ext.create('mda.view.gmo.gma.servicio.vpmain', {renderTo: Ext.getBody()});
    }

});
