/*
 * File: app/mda/controller/gmo/global/utiles/ctrfuncion.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('gma.controller.gmo.global.utiles.ctrfuncion', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.global.utiles.ctrfuncion'
    ],

    fn_AjaxRequest: function(as_params, as_url, cb_function) {
                    var respuesta='';

                     Ext.Ajax.request({
                        method:'POST',
                        url:as_url,
                        params:as_params,

                        success:function(result,request){

                            respuesta=Ext.JSON.decode(result.responseText);

                            if (respuesta.success){
                                cb_function(true);
                            }else{
                                Ext.Msg.alert('Mensaje',respuesta.msgError);
                                cb_function(false);
                            }
                        },
                        failure:function(result,request){
                            respuesta=Ext.JSON.decode(result.responseText);
                            Ext.Msg.alert('Mensaje Failure',respuesta.msgError);
                            cb_function(false);
                        }
                    });
    },

    fn_FormSubmit: function(form, as_params, as_url, cb_function, resultdata) {
                form.submit({
                    url:as_url,
                    method:'POST',
                    scope:this,
                    params:as_params,
                    success:function(form,action){
                        resultdata= Ext.JSON.decode(action.response.responseText);
                        cb_function(true,resultdata);
                    },
                    failure:function(form,action){
                        resultdata=Ext.JSON.decode(action.response.responseText);
                        cb_function(false,resultdata);
                    }

                });
    }

});
