/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'gmo.global.glbpais.mdglbpais',
        'gmo.gma.responsable.mdresponsable',
        'gmo.gma.servicio.mdservicio'
    ],
    stores: [
        'gmo.global.glbpais.stglbpais',
        'gmo.gma.responsable.stresponsable',
        'gmo.gma.responsable.stresponsablenew',
        'gmo.gma.servicio.stservicio',
        'gmo.gma.servicio.stserviciocmb'
    ],
    views: [
        'gmo.gma.responsable.vpmain',
        'gmo.gma.responsable.winMtto'
    ],
    appFolder: 'app/mda',
    appProperty: 'mda',
    controllers: [
        'gmo.gma.responsable.ctrMain',
        'gmo.gma.responsable.ctrMtto'
    ],
    name: 'mda',
    title: 'Mantenimiento de Responsables',

    launch: function() {
        Ext.create('mda.view.gmo.gma.responsable.vpmain', {renderTo: Ext.getBody()});
    }

});
