/*
 * File: app/mda/model/gmo/gma/atributo/mdprioridad.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.model.gmo.gma.atributo.mdprioridad', {
    extend: 'Ext.data.Model',

    alternateClassName: [
        'gmo.gma.atributo.mdprioridad'
    ],
    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'codigo',

    fields: [
        {
            name: 'codigo',
            type: 'int'
        },
        {
            name: 'descripcion',
            type: 'string'
        }
    ]
});