/*
 * File: app/mda/view/gmo/gma/responsable/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('gma.view.gmo.gma.responsable.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gma.responsable.winMtto'
    ],
    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.FieldContainer',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.column.CheckColumn',
        'Ext.form.field.Hidden'
    ],

    height: 521,
    itemId: 'wingmaresponsable',
    width: 764,
    layout: 'fit',
    title: 'Listado de Temas Pendientes de Asignacion x Resolutor',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'frmgmaresponsable',
                    layout: 'fit',
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/process/lst_gma_responsable.php',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Menu de opciones:'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnguardar',
                                    iconCls: 'btnSave',
                                    text: 'Guardar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btncerrar',
                                    iconCls: 'btnClose',
                                    text: 'Cerrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            height: 120,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Datos de Resolutor:',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'srv_denominacion',
                                            fieldLabel: 'Servicio',
                                            name: 'srv_denominacion',
                                            submitValue: false,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'per_nombrecompleto',
                                            fieldLabel: 'Nombres:',
                                            name: 'per_nombrecompleto',
                                            submitValue: false,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'rse_niveldescripcion',
                                                    fieldLabel: 'Nivel:',
                                                    name: 'rse_niveldescripcion',
                                                    submitValue: false,
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'pai_denominacion',
                                                    margin: '0 0 0 10',
                                                    fieldLabel: 'Region',
                                                    name: 'pai_denominacion',
                                                    submitValue: false,
                                                    readOnly: true
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'grdgmarequerimiento',
                                    store: 'gmo.gma.responsable.strequerimientopendiente',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Temas pendientes de asignar resolutor seleccionado'
                                                },
                                                {
                                                    xtype: 'tbfill'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnrecuperar',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnseleccionar',
                                                    width: 100,
                                                    iconCls: 'btnSelect',
                                                    text: 'Seleccionar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretirar',
                                                    width: 100,
                                                    iconCls: 'btnDelete',
                                                    text: 'De-seleccionar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                }
                                            ]
                                        }
                                    ],
                                    viewConfig: {
                                        itemId: 'grvgmarequerimiento'
                                    },
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'rqe_codigo',
                                            text: 'Rqe Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'rpe_codigo',
                                            text: 'Rpe Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 589,
                                            dataIndex: 'rqe_denominacion',
                                            text: 'Tema o Requerimiento'
                                        },
                                        {
                                            xtype: 'checkcolumn',
                                            dataIndex: 'rqe_seleccionado',
                                            text: 'Seleccionar'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'accion',
                            fieldLabel: 'Label',
                            name: 'accion'
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'rse_codigo',
                            fieldLabel: 'Label',
                            name: 'rse_codigo'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});