/*
 * File: app/mda/view/gmo/gma/servicio/vpmain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.view.gmo.gma.servicio.vpmain', {
    extend: 'Ext.panel.Panel',

    alternateClassName: [
        'gmo.gma.servicio.vpmain'
    ],
    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.grid.column.Number',
        'Ext.toolbar.Paging'
    ],

    height: 600,
    itemId: 'vpmaingmaServicio',
    width: 1200,
    layout: 'border',
    title: 'Mantenimiento de Servicios y Temas',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'north',
                    height: 150,
                    itemId: 'grdServicio',
                    store: 'gmo.gma.servicio.stservicio',
                    viewConfig: {
                        itemId: 'mygridview'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtcriterio',
                                    fieldLabel: 'Criterio',
                                    labelWidth: 50,
                                    emptyText: 'Especificar criterio de busqueda'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRecuperar',
                                    iconCls: 'btnRetrieve',
                                    text: 'Recuperar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnNuevo',
                                    iconCls: 'btnNew',
                                    text: 'Nuevo'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnModificar',
                                    iconCls: 'btnEdit',
                                    text: 'Modificar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnAnular',
                                    iconCls: 'btnDelete',
                                    text: 'Anular'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCerrar',
                                    iconCls: 'btnClose',
                                    text: 'Cerrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'gmo.gma.servicio.stservicio'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'srv_codigo',
                            text: 'Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 549,
                            dataIndex: 'srv_denominacion',
                            text: 'Denominacion'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    itemId: 'grdRequerimiento',
                    store: 'gmo.gma.requerimiento.strequerimiento',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtcriteriorequerimiento',
                                    fieldLabel: 'Criterio',
                                    labelWidth: 50,
                                    emptyText: 'Especificar criterio de busqueda'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRetrieverequerimiento',
                                    iconCls: 'btnRetrieve',
                                    text: 'Recuperar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnNuevorequerimiento',
                                    iconCls: 'btnNew',
                                    text: 'Nuevo'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnModificarrequerimiento',
                                    iconCls: 'btnEdit',
                                    text: 'Modificar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnAnularrequerimiento',
                                    iconCls: 'btnDelete',
                                    text: 'Anular'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'rqe_codigo',
                            text: 'Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'srv_codigo',
                            text: 'Srv Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'srv_denominacion',
                            text: 'Denominacion'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 570,
                            dataIndex: 'rqe_denominacion',
                            text: 'Rqe Denominacion'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'rqe_prioridad',
                            text: 'Rqe Prioridad',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 182,
                            dataIndex: 'des_prioridad',
                            text: 'Prioridad'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 182,
                            align: 'center',
                            dataIndex: 'rqe_tiemporpta',
                            text: 'Tiempo Max. Respuesta (Hrs.)'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});