/*
 * File: app/mda/view/gmo/gma/servicio/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mda.view.gmo.gma.servicio.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gma.servicio.winMtto'
    ],
    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text'
    ],

    height: 140,
    itemId: 'wingmaServicio',
    width: 597,
    layout: 'fit',
    title: 'Mantenimiento de Servicios',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'frmServicio',
                    layout: 'fit',
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/process/lst_gma_servicio.php',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Menu de opciones:'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnGuardar',
                                    iconCls: 'btnSave',
                                    text: 'Guardar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCerrar',
                                    iconCls: 'btnClose',
                                    text: 'Cerrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            itemId: 'srv_codigo',
                            fieldLabel: 'Label',
                            name: 'srv_codigo',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'accion',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'srv_denominacion',
                            fieldLabel: 'Denominacion',
                            labelAlign: 'top',
                            name: 'srv_denominacion',
                            fieldStyle: 'font-size:11px; text-transform: uppercase;',
                            allowBlank: false,
                            emptyText: 'Especifique denominacion del servicio '
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});